/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 * Sample JavaFX application with GUI declared in FXML file.
 */
public class App extends Application {

    @Override
    public final void start(final Stage primaryStage) throws Exception {
        final Scene root = (Scene)FXMLLoader.load(getClass().getResource("/MainGui.fxml"));
        
        primaryStage.setOnCloseRequest((e) -> { 
           Platform.exit();
           System.exit(0);       
        });
        
        primaryStage.setTitle("Water level App");
        primaryStage.setScene(root);
        primaryStage.show();
    }

    private static void run(final String[] args) {
        launch(args);
    }

    /**
     * Entry point class.
     */
    public static final class Main {
        private Main() {
            // the constructor will never be called directly.
        }

        /**
         * Program's entry point.
         * @param args
         */
        public static void main(final String... args) {
            App.run(args);
        }
    }

}
